apiVersion: v1
kind: Service
metadata:
  name: revolut-devops-tool
spec:
  type: LoadBalancer
  selector:
    app: revolut-devops-tool
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
